//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularForm.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AngularFormEntities : DbContext
    {
        public AngularFormEntities()
            : base("name=AngularFormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Employer> Employers { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Hobbie> Hobbies { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Reference> References { get; set; }
    }
}
